# Generated by Django 4.2.9 on 2024-01-21 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('materials', models.CharField(max_length=100)),
                ('pattern', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'product_table',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('seller_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('seller_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=100)),
                ('created_date', models.DateField(auto_now=True)),
                ('status', models.CharField(default='pending', max_length=100)),
            ],
            options={
                'db_table': 'seller_table',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('size_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=100)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='sellerapp.product')),
            ],
            options={
                'db_table': 'size_table',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellerapp.seller'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsapp.subcategory'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('image_file', models.ImageField(upload_to='images/')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sellerapp.product')),
            ],
            options={
                'db_table': 'image_table',
            },
        ),
    ]
