# Generated by Django 4.2.9 on 2024-01-29 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Western',
            fields=[
                ('western_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='westerns', to='sellerapp.product')),
            ],
            options={
                'db_table': 'western_table',
            },
        ),
        migrations.CreateModel(
            name='Tshirt',
            fields=[
                ('tshirt_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tshirts', to='sellerapp.product')),
            ],
            options={
                'db_table': 'tshirt_table',
            },
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('shirt_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shirts', to='sellerapp.product')),
            ],
            options={
                'db_table': 'shirt_table',
            },
        ),
        migrations.CreateModel(
            name='Saree',
            fields=[
                ('saree_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sarees', to='sellerapp.product')),
            ],
            options={
                'db_table': 'saree_table',
            },
        ),
        migrations.CreateModel(
            name='Kurta',
            fields=[
                ('kurta_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kurtas', to='sellerapp.product')),
            ],
            options={
                'db_table': 'kurta_table',
            },
        ),
        migrations.CreateModel(
            name='Jeans',
            fields=[
                ('jeans_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jeans', to='sellerapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Boysdrs',
            fields=[
                ('boys_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boysdrss', to='sellerapp.product')),
            ],
            options={
                'db_table': 'boys_table',
            },
        ),
    ]
