# Generated by Django 4.2.9 on 2024-01-29 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0002_western_tshirt_shirt_saree_kurta_jeans_boysdrs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boysdrs',
            name='description',
        ),
        migrations.RemoveField(
            model_name='jeans',
            name='description',
        ),
        migrations.RemoveField(
            model_name='kurta',
            name='description',
        ),
        migrations.RemoveField(
            model_name='saree',
            name='description',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tshirt',
            name='description',
        ),
        migrations.RemoveField(
            model_name='western',
            name='description',
        ),
    ]
