# Generated by Django 4.2.9 on 2024-02-04 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminsapp', '0002_event'),
        ('sellerapp', '0003_remove_boysdrs_description_remove_jeans_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offer_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('discount', models.CharField(max_length=100)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsapp.event')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='sellerapp.product')),
            ],
            options={
                'db_table': 'offer_table',
            },
        ),
    ]
