# Generated by Django 4.2.9 on 2024-02-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_remove_user_address_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
