# Generated by Django 4.2.9 on 2024-02-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
