# Generated by Django 4.2.9 on 2024-02-02 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0003_remove_boysdrs_description_remove_jeans_description_and_more'),
        ('usersapp', '0005_alter_review_review_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='sellerapp.product'),
        ),
    ]
