# Generated by Django 4.2.9 on 2024-02-05 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0008_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
