# Generated by Django 4.2.9 on 2024-02-05 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0005_alter_product_price'),
        ('usersapp', '0009_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersapp.address')),
                ('offer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellerapp.offer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellerapp.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersapp.user')),
            ],
            options={
                'db_table': 'order_table',
            },
        ),
    ]
