# Generated by Django 4.2.9 on 2024-02-07 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0005_alter_product_price'),
        ('usersapp', '0010_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='offer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sellerapp.offer'),
        ),
    ]
